apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-console-httpproxy
  namespace: minio
spec:
  virtualhost:
    fqdn: minio.devops.tanzu-altair.com
  routes:
    - services:
        - name: minio-console
          port: 9001
    - conditions:
      - prefix: /ws/objectManager
      enableWebsockets: true
      services:
        - name: minio-console
          port: 9001
