apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: client-springboot-template
spec:
  params:
    - name: gitrevision
      description: git revision(master branch name)
      default: master
    - name: giturl
      description: git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: client-springboot-pipeline-
      spec:
        serviceAccountName: pipeline-account
        pipelineRef:
          name: full
        params:
          - name: APP_IMAGE
            value: "altaira/client-springboot"
          - name: GIT_URL
            value: "https://github.com/altaira-hyun/spring-cloud.git"
          - name: GIT_SUBDIR
            value: ""
          - name: GIT_BRANCH
            value: "main"
          - name: GIT_EMAIL
            value: "altair@megazone.com"
          - name: GIT_USERNAME
            value: "altair"
          - name: GIT_REPO_NAME
            value: "spring-cloud"
          - name: BUILD_SUBDIR
            value: "client-springboot"
          - name: MANIFEST_DIR
            value: "manifest"
          - name: REPO_TYPE
            value: "git"
