apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jenkins-httpproxy
  namespace: jenkins
spec:
  virtualhost:
    fqdn: jenkins.devops.tanzu-altair.com
  routes:
    - services:
        - name: jenkins
          port: 8080
