apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: client-springboot
spec:
  serviceAccountName: pipeline-account # Only needed if you set up authorization
  pipelineRef:
    name: full
  workspaces:
    - name: source-workspace
      subPath: source
      persistentVolumeClaim:
        claimName: pipeline-pvc
    - name: cache-workspace
      subPath: cache
      persistentVolumeClaim:
        claimName: pipeline-pvc
    - name: git-workspace
      emptyDir: {}
  params:
    - name: APP_IMAGE
      value: "altaira/client-springboot" # This defines the name of output image
    - name: GIT_URL
      value: "https://github.com/altaira-hyun/spring-cloud.git"
    - name: GIT_SUBDIR
      value: ""
    - name: GIT_BRANCH
      value: "main"
    - name: GIT_EMAIL
      value: "altair@megazone.com"
    - name: GIT_USERNAME
      value: "altair"
    - name: GIT_REPO_NAME
      value: "spring-cloud"
    - name: BUILD_SUBDIR
      value: "client-springboot"
    - name: MANIFEST_DIR
      value: "manifest"
    - name: REPO_TYPE
      value: "git"
