apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: kpack-builder
  namespace: default
spec:
  serviceAccountName: kpack-account
  tag: registry.altair-lab.com/kpack/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
