---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: argocd-ca-issuer
 namespace: argocd
spec:
  ca:
    secretName: argocd-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  commonName: argocd
  dnsNames:
  - argocd.tanzu-altair.com
  - "*.tanzu-altair.com"
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: argocd-ca-issuer
  renewBefore: 360h0m0s
  secretName: argocd-tls
  usages:
  - server auth
  - client auth
